DROP TABLE `COMMENT`;

CREATE TABLE `COMMENT`
(
    `TASK_CODE`         CHAR(76)        NOT NULL    COMMENT '所属タスク',
    `INDEX`             TINYINT(1)      NOT NULL    COMMENT '表示順',
    `TEXT`              VARCHAR(1024)   NOT NULL    COMMENT '内容',
    `CREATE_ID`         VARCHAR(16)     NOT NULL    COMMENT '作成ユーザーID',
    `CREATE_DATETIME`   DATETIME        NOT NULL    COMMENT '作成日時',
    `UPDATE_ID`         VARCHAR(16)     NOT NULL    COMMENT '更新ユーザーID',
    `UPDATE_DATETIME`   DATETIME        NOT NULL    COMMENT '更新日時'
);

ALTER TABLE `COMMENT` ADD CONSTRAINT PK_COMMENT PRIMARY KEY (
    `TASK_CODE`,
    `INDEX`
);

ALTER TABLE `COMMENT` COMMENT 'コメントテーブル';
