DROP TABLE IF EXISTS  `COMMENT_FILE`;

CREATE TABLE `COMMENT_FILE`
(
    `TASK_CODE` VARCHAR(256)    NOT NULL    COMMENT 'コード',
    `INDEX`     TINYINT(1)      NOT NULL    COMMENT '番号',
    `FILE_PATH`      VARCHAR(256)    NOT NULL    COMMENT '画像ファイルパス'
);

ALTER TABLE `COMMENT_FILE` COMMENT 'コメント添付画像テーブル';
