ALTER TABLE `USER` ADD FOREIGN KEY `MAIL` REFERENCES `USER_PROJECT`(`MAIL`);
ALTER TABLE `PROJECT` ADD FOREIGN KEY `PROJECT_CODE` REFERENCES `USER_PROJECT`(`PROJECT_CODE`);
ALTER TABLE `LIST` ADD FOREIGN KEY `PROJECT_CODE` REFERENCES `PROJECT`(`PROJECT_CODE`);
ALTER TABLE `TASK` ADD FOREIGN KEY `LIST_CODE` REFERENCES `LIST`(`LIST_CODE`);
ALTER TABLE `COMMENT` ADD FOREIGN KEY `TASK_CODE` REFERENCES `TASK`(`TASK_CODE`);