DROP TABLE `PROJECT`;

CREATE TABLE `PROJECT`
(
    `PROJECT_CODE`      CHAR(36)        NOT NULL    COMMENT 'GUID',
    `NAME`              VARCHAR(64)     NOT NULL    COMMENT 'プロジェクト名',
    `CREATE_ID`         VARCHAR(16)     NOT NULL    COMMENT '作成ユーザーID',
    `CREATE_DATETIME`   DATETIME        NOT NULL    COMMENT '作成日時',
    `UPDATE_ID`         VARCHAR(16)     NOT NULL    COMMENT '更新ユーザーID',
    `UPDATE_DATETIME`   DATETIME        NOT NULL    COMMENT '更新日時'
);

ALTER TABLE `PROJECT` ADD CONSTRAINT PK_PROJECT PRIMARY KEY (
    `PROJECT_CODE`
);

ALTER TABLE `PROJECT` COMMENT 'プロジェクトテーブル';
