DROP TABLE IF EXISTS  `TASK_IMAGE`;

CREATE TABLE `TASK_IMAGE`
(
    `TASK_CODE`  VARCHAR(256)    NOT NULL    COMMENT 'タスクコード',
    `FILE_PATH`  VARCHAR(256)    NOT NULL    COMMENT '画像ファイルパス'
);

ALTER TABLE `TASK_IMAGE` COMMENT 'タスク添付画像テーブル';
