DROP TABLE IF EXISTS  `TEST`;

CREATE TABLE `TEST`
(
    `MAIL`  VARCHAR(256)    NOT NULL    COMMENT 'DBFacadeテスト',
    `NAME`  VARCHAR(32) NOT NULL    COMMENT 'DBFacadeテスト'
);

ALTER TABLE `TEST` ADD CONSTRAINT PK_TEST PRIMARY KEY (
    `MAIL`
);

ALTER TABLE `TEST` COMMENT 'ユーザーテーブル';
