DROP TABLE `USER_ADDRESS`;

CREATE TABLE `USER_ADDRESS`
(
    `USER_ID`   VARCHAR(16) NOT NULL    COMMENT 'ユーザーID',
    `ADDRESS`   VARCHAR(15) NOT NULL    COMMENT '接続元IPアドレス'
);

ALTER TABLE `USER_ADDRESS` COMMENT 'ユーザー・IPアドレス紐付テーブル';
